import type { NextPage } from 'next'
import Head from 'next/head'
import {Box, Button, Container} from "@chakra-ui/react";
import {useEffect, useRef} from "react";
// @ts-ignore

function PictureTest() {
    const handleButtonClick = () => {
        window.Caman("#img1", function () {
            console.log(this);
            // this.brightness(10).contrast(20).noise(50).render(function () {
            //     alert("Done!");
            // });
            // this.newLayer(function () {
            //     // There are many blending modes, more below.
            //     this.setBlendingMode('multiply');
            //     this.opacity(10);
            //     this.copyParent();
            //
            //     this.filter.gamma(0.8);
            //     this.filter.contrast(50);
            //
            //     /*
            //      * Yep, you can stack multiple layers! The further a layer is nested, the higher up on the layer
            //      * stack it will be.
            //      */
            //     this.newLayer(function () {
            //         this.setBlendingMode('softLight');
            //         this.opacity(10);
            //         this.fillColor('#f49600');
            //     });
            //
            //     this.filter.exposure(10);
            // });
            this.newLayer(function () {
                this.setBlendingMode('softLight');
                this.opacity(50);

                this.overlayImage('/02.jpg');
            });

            this.exposure(20);
            this.gamma(0.8);
            this.render();
        })
    }
    return <Box>
        <img src={"/01.jpg"} />
        <img id={"img1"} data-caman="saturation(-80) brightness(90) vignette('10%')" src={"/01.jpg"} />
        <Button onClick={handleButtonClick}>Transofrm</Button>
    </Box>;
}

const Home: NextPage = () => {
  return (
    <Container maxWidth={"container.lg"} minHeight={"100vh"}>
        <Head>
            <title>Image Processing</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>

        <main>
            <Container minHeight={"80vh"}>
                <PictureTest/>
                <div className="test-0">
                        <div className="time"></div>
                </div>
            </Container>
        </main>

        <footer>
            Dmitrijs Voronovs
        </footer>
    </Container>
  )
}

export default Home
