import type { NextPage } from "next";
import Head from "next/head";
import { Space } from "antd";
import { ImageEditor } from "../components/ImageEditor";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Image Processing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          height: "100vh",
          width: "100%",
          overflowY: "hidden",
          background: "#fffcf5",
        }}
      >
        <ImageEditor />
      </main>

      <footer
        style={{
          textAlign: "left",
          position: "absolute",
          bottom: "15px",
          left: "15px",
        }}
      >
        Made by Dmitry Voronov
      </footer>
    </>
  );
};

export default Home;
