import type { NextPage } from "next";
import Head from "next/head";
import { Space } from "antd";
import { ImageEditor } from "../components/ImageEditor";

const Home: NextPage = () => {
  return (
    <Space direction={"vertical"} style={{ minHeight: "100vh" }}>
      <Head>
        <title>Image Processing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Space style={{ minHeight: "80vh", padding: 24 }}>
          <ImageEditor />
        </Space>
      </main>

      <footer style={{ textAlign: "center" }}>Dmitrijs Voronovs</footer>
    </Space>
  );
};

export default Home;
